name: Action that runs upon PR

on:
  pull_request:

jobs:
  log-message:
    runs-on: ubuntu-latest
    steps:
      - name: Log message to console
        run: echo 'A pull request has been made and it should fail' && exit 1
        shell: bash